import { initializeApp } from "firebase/app";
import { getFirestore, collection, doc, setDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyBuxDW_-kwNxSNibO-WUGf1LYAAVsC03sM",
  authDomain: "furrmate-61970.firebaseapp.com",
  projectId: "furrmate-61970",
  storageBucket: "furrmate-61970.firebasestorage.app",
  messagingSenderId: "364051552649",
  appId: "1:364051552649:web:354cea0ffdad924d31a958",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const PETS = [
  {
    id: "pet_001",
    name: "Milo",
    species: "dog",
    breed: "Golden Retriever",
    age: 18,
    ageLabel: "1.5 years",
    size: "large",
    gender: "male",
    photos: ["https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=600&q=80"],
    bio: "Milo is a sunshine-in-dog-form Golden Retriever who greets everyone with a wagging tail and a tennis ball in his mouth. He loves morning runs, belly rubs, and snoozing by the fireplace. Great with kids and other dogs.",
    traits: ["Playful", "Gentle", "Loyal", "Energetic"],
    medicalRecords: [
      { id: "mr_001_1", name: "Annual Vaccines", date: "2025-11-01", type: "vaccination", vet: "Dr. Patel", notes: "Rabies, DHPP, Bordetella all up to date" },
    ],
    shelterId: "shelter_001",
    shelterName: "Happy Paws Rescue",
    location: { lat: 37.3382, lng: -121.8863, city: "San Jose", state: "CA" },
    status: "available",
    vaccinated: true,
    neutered: true,
    goodWithKids: true,
    goodWithPets: true,
    adoptionFee: 250,
    postedAt: "2026-03-10T10:00:00Z",
    color: "Golden",
    weight: "65 lbs",
  },
  {
    id: "pet_002",
    name: "Luna",
    species: "cat",
    breed: "Siamese",
    age: 36,
    ageLabel: "3 years",
    size: "small",
    gender: "female",
    photos: ["https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&q=80"],
    bio: "Luna is a talkative Siamese beauty who will hold full conversations with you and demand your attention at 2am. She adores window perches, laser pointers, and sleeping in warm laundry. Best as the only pet.",
    traits: ["Vocal", "Affectionate", "Curious", "Independent"],
    medicalRecords: [
      { id: "mr_002_1", name: "Spay & Wellness", date: "2025-08-15", type: "surgery", vet: "Dr. Kim", notes: "Fully recovered, all vaccines current" },
    ],
    shelterId: "shelter_002",
    shelterName: "City Cat Coalition",
    location: { lat: 34.0522, lng: -118.2437, city: "Los Angeles", state: "CA" },
    status: "available",
    vaccinated: true,
    neutered: true,
    goodWithKids: true,
    goodWithPets: false,
    adoptionFee: 125,
    postedAt: "2026-03-12T09:00:00Z",
    color: "Seal Point",
    weight: "9 lbs",
  },
  {
    id: "pet_003",
    name: "Bear",
    species: "dog",
    breed: "Bernese Mountain Dog",
    age: 8,
    ageLabel: "8 months",
    size: "large",
    gender: "male",
    photos: ["https://images.unsplash.com/photo-1558788353-f76d92427f16?w=600&q=80"],
    bio: "Bear is a fluffy giant who doesn't know he's still a puppy. He stumbles into hearts everywhere he goes. He's learning basic commands quickly and loves cold weather, cuddles, and stealing socks. Needs a yard.",
    traits: ["Gentle Giant", "Playful", "Stubborn", "Cuddly"],
    medicalRecords: [
      { id: "mr_003_1", name: "Puppy Vaccines", date: "2025-10-20", type: "vaccination", vet: "Dr. Torres", notes: "DHPP series complete, Rabies given" },
    ],
    shelterId: "shelter_001",
    shelterName: "Happy Paws Rescue",
    location: { lat: 37.3382, lng: -121.8863, city: "San Jose", state: "CA" },
    status: "available",
    vaccinated: true,
    neutered: false,
    goodWithKids: true,
    goodWithPets: true,
    adoptionFee: 300,
    postedAt: "2026-03-14T11:00:00Z",
    color: "Tricolor",
    weight: "70 lbs",
  },
  {
    id: "pet_004",
    name: "Cleo",
    species: "cat",
    breed: "Orange Tabby",
    age: 60,
    ageLabel: "5 years",
    size: "medium",
    gender: "female",
    photos: ["https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&q=80"],
    bio: "Cleo is a mellow orange tabby who loves naps in sunbeams and slow-blinking at her favorite humans. She's lived with other cats before and gets along fine once properly introduced. Perfect lap cat.",
    traits: ["Calm", "Friendly", "Low-maintenance", "Lap cat"],
    medicalRecords: [
      { id: "mr_004_1", name: "Dental Cleaning", date: "2025-09-05", type: "dental", vet: "Dr. Nguyen", notes: "Healthy teeth, annual cleaning done" },
    ],
    shelterId: "shelter_002",
    shelterName: "City Cat Coalition",
    location: { lat: 34.0522, lng: -118.2437, city: "Los Angeles", state: "CA" },
    status: "available",
    vaccinated: true,
    neutered: true,
    goodWithKids: true,
    goodWithPets: true,
    adoptionFee: 100,
    postedAt: "2026-03-08T08:00:00Z",
    color: "Orange",
    weight: "11 lbs",
  },
  {
    id: "pet_005",
    name: "Rocket",
    species: "dog",
    breed: "Border Collie Mix",
    age: 24,
    ageLabel: "2 years",
    size: "medium",
    gender: "male",
    photos: ["https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80"],
    bio: "Rocket lives up to his name — this Border Collie mix has endless energy and an unstoppable desire to play fetch. He's super smart, knows 15 commands, and needs a person who will keep him mentally stimulated. Not for couch potatoes.",
    traits: ["Intelligent", "Energetic", "Trainable", "Athletic"],
    medicalRecords: [
      { id: "mr_005_1", name: "Annual Checkup", date: "2026-01-10", type: "checkup", vet: "Dr. Patel", notes: "Excellent health, all vaccines current" },
    ],
    shelterId: "shelter_003",
    shelterName: "Second Chance Animal Rescue",
    location: { lat: 47.6062, lng: -122.3321, city: "Seattle", state: "WA" },
    status: "available",
    vaccinated: true,
    neutered: true,
    goodWithKids: true,
    goodWithPets: true,
    adoptionFee: 200,
    postedAt: "2026-03-15T14:00:00Z",
    color: "Black & White",
    weight: "45 lbs",
  },
  {
    id: "pet_006",
    name: "Biscuit",
    species: "rabbit",
    breed: "Holland Lop",
    age: 14,
    ageLabel: "14 months",
    size: "small",
    gender: "male",
    photos: ["https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&q=80"],
    bio: "Biscuit is a floppy-eared Holland Lop who binkies around his pen every morning like he just won the lottery. He loves fresh parsley, cardboard tunnels, and will thump loudly if his dinner is late. Great first bunny.",
    traits: ["Curious", "Active", "Sociable", "Gentle"],
    medicalRecords: [
      { id: "mr_006_1", name: "Wellness Exam", date: "2025-12-01", type: "checkup", vet: "Dr. Chen", notes: "Healthy weight, teeth in good condition" },
    ],
    shelterId: "shelter_003",
    shelterName: "Second Chance Animal Rescue",
    location: { lat: 47.6062, lng: -122.3321, city: "Seattle", state: "WA" },
    status: "available",
    vaccinated: false,
    neutered: true,
    goodWithKids: true,
    goodWithPets: false,
    adoptionFee: 75,
    postedAt: "2026-03-16T10:00:00Z",
    color: "Cream",
    weight: "4 lbs",
  },
  {
    id: "pet_007",
    name: "Nala",
    species: "dog",
    breed: "Labrador Retriever",
    age: 48,
    ageLabel: "4 years",
    size: "large",
    gender: "female",
    photos: ["https://images.unsplash.com/photo-1560743641-3914f2c45636?w=600&q=80"],
    bio: "Nala is a chocolate Lab with the sweetest disposition you'll ever find. She was surrendered when her family relocated and has been heartbroken ever since. She wants nothing more than a couch to call her own and a human to love.",
    traits: ["Calm", "Loving", "Well-trained", "Loyal"],
    medicalRecords: [
      { id: "mr_007_1", name: "Full Wellness", date: "2026-02-01", type: "checkup", vet: "Dr. Torres", notes: "Hip X-rays clear, all vaccines current" },
      { id: "mr_007_2", name: "Bordetella Booster", date: "2026-02-01", type: "vaccination", vet: "Dr. Torres" },
    ],
    shelterId: "shelter_004",
    shelterName: "Austin Animal Center",
    location: { lat: 30.2672, lng: -97.7431, city: "Austin", state: "TX" },
    status: "available",
    vaccinated: true,
    neutered: true,
    goodWithKids: true,
    goodWithPets: true,
    adoptionFee: 150,
    postedAt: "2026-03-05T09:00:00Z",
    color: "Chocolate",
    weight: "60 lbs",
  },
  {
    id: "pet_008",
    name: "Mango",
    species: "bird",
    breed: "Sun Conure",
    age: 24,
    ageLabel: "2 years",
    size: "small",
    gender: "male",
    photos: ["https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&q=80"],
    bio: "Mango is a vibrant Sun Conure who lights up every room with his neon feathers and big personality. He says 'pretty bird' and 'good morning', loves head scratches, and will dance to any music. Needs daily out-of-cage time.",
    traits: ["Talkative", "Playful", "Affectionate", "Loud"],
    medicalRecords: [
      { id: "mr_008_1", name: "Avian Wellness", date: "2025-11-15", type: "checkup", vet: "Dr. Rivera", notes: "Healthy weight, feathers in great condition" },
    ],
    shelterId: "shelter_004",
    shelterName: "Austin Animal Center",
    location: { lat: 30.2672, lng: -97.7431, city: "Austin", state: "TX" },
    status: "available",
    vaccinated: false,
    neutered: false,
    goodWithKids: false,
    goodWithPets: false,
    adoptionFee: 350,
    postedAt: "2026-03-18T13:00:00Z",
    color: "Orange & Yellow",
    weight: "0.25 lbs",
  },
  {
    id: "pet_009",
    name: "Shadow",
    species: "cat",
    breed: "Domestic Shorthair",
    age: 84,
    ageLabel: "7 years",
    size: "medium",
    gender: "male",
    photos: ["https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&q=80"],
    bio: "Shadow is a sleek all-black cat with golden eyes that seem to see straight into your soul. He's a senior who loves predictability, quiet evenings, and sleeping at your feet. Shy at first but deeply bonded once he trusts you.",
    traits: ["Calm", "Independent", "Gentle", "Quiet"],
    medicalRecords: [
      { id: "mr_009_1", name: "Senior Wellness Panel", date: "2026-01-20", type: "checkup", vet: "Dr. Kim", notes: "Bloodwork normal for age, thyroid healthy" },
    ],
    shelterId: "shelter_005",
    shelterName: "Brooklyn Bridge Animal Welfare",
    location: { lat: 40.6782, lng: -73.9442, city: "Brooklyn", state: "NY" },
    status: "available",
    vaccinated: true,
    neutered: true,
    goodWithKids: false,
    goodWithPets: false,
    adoptionFee: 75,
    postedAt: "2026-02-28T10:00:00Z",
    color: "Black",
    weight: "12 lbs",
  },
  {
    id: "pet_010",
    name: "Daisy",
    species: "dog",
    breed: "Beagle",
    age: 30,
    ageLabel: "2.5 years",
    size: "medium",
    gender: "female",
    photos: ["https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600&q=80"],
    bio: "Daisy is a nose-to-the-ground Beagle who treats every walk like a grand investigation. She's friendly with everyone she meets, loves howling along to music, and will happily share your snacks if you let her. Needs a fenced yard.",
    traits: ["Friendly", "Curious", "Vocal", "Food-motivated"],
    medicalRecords: [
      { id: "mr_010_1", name: "Annual Vaccines", date: "2025-10-10", type: "vaccination", vet: "Dr. Nguyen", notes: "All core vaccines given, heartworm negative" },
    ],
    shelterId: "shelter_005",
    shelterName: "Brooklyn Bridge Animal Welfare",
    location: { lat: 40.6782, lng: -73.9442, city: "Brooklyn", state: "NY" },
    status: "available",
    vaccinated: true,
    neutered: true,
    goodWithKids: true,
    goodWithPets: true,
    adoptionFee: 175,
    postedAt: "2026-03-20T15:00:00Z",
    color: "Tricolor",
    weight: "25 lbs",
  },
];

const SHELTERS = [
  { id: "shelter_001", name: "Happy Paws Rescue", address: "123 Oak Street", city: "San Jose", state: "CA", phone: "(408) 555-0101", email: "adopt@happypaws.org", description: "A no-kill shelter serving the South Bay since 2005.", location: { lat: 37.3382, lng: -121.8863 }, petCount: 0, established: "2005", avatar: "🐾" },
  { id: "shelter_002", name: "City Cat Coalition", address: "456 Sunset Blvd", city: "Los Angeles", state: "CA", phone: "(213) 555-0202", email: "adopt@citycat.org", description: "LA's premier cat rescue and TNR organization.", location: { lat: 34.0522, lng: -118.2437 }, petCount: 0, established: "2010", avatar: "🐱" },
  { id: "shelter_003", name: "Second Chance Animal Rescue", address: "789 Pine Ave", city: "Seattle", state: "WA", phone: "(206) 555-0303", email: "adopt@secondchance.org", description: "Giving every animal a second shot at a loving home.", location: { lat: 47.6062, lng: -122.3321 }, petCount: 0, established: "2008", avatar: "🐶" },
  { id: "shelter_004", name: "Austin Animal Center", address: "321 Congress Ave", city: "Austin", state: "TX", phone: "(512) 555-0404", email: "adopt@austinanimals.org", description: "Austin's largest open-intake shelter and adoption center.", location: { lat: 30.2672, lng: -97.7431 }, petCount: 0, established: "1999", avatar: "🌟" },
  { id: "shelter_005", name: "Brooklyn Bridge Animal Welfare", address: "99 Atlantic Ave", city: "Brooklyn", state: "NY", phone: "(718) 555-0505", email: "adopt@bbaw.org", description: "Connecting NYC animals with loving families since 2003.", location: { lat: 40.6782, lng: -73.9442 }, petCount: 0, established: "2003", avatar: "🗽" },
];

async function seed() {
  console.log("Seeding 10 pet listings and 5 shelters...\n");

  for (const shelter of SHELTERS) {
    await setDoc(doc(collection(db, "shelters"), shelter.id), shelter);
    console.log(`✓ Shelter: ${shelter.name}`);
  }

  for (const pet of PETS) {
    await setDoc(doc(collection(db, "pets"), pet.id), pet);
    console.log(`✓ Pet: ${pet.name} (${pet.breed}) — ${pet.location.city}, ${pet.location.state}`);
  }

  console.log("\nDone! 10 pets and 5 shelters added to Firestore.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
